#!/bin/bash

#if outfile not specified
if [ "$1" != "" ]; then
OUTFILE=$1
else
OUTFILE=stressTestResults
fi

echo " " &>> $OUTFILE
echo "Stress tests for balanced sieve" &>> $OUTFILE
echo "===============================" &>> $OUTFILE

#using 12 threads on caper for testing
nthreads=12

for n in {1..18}
  do
  ((SIZE=10**n))
  echo " " &>> $OUTFILE
  echo "n = 1x10^$n" &>> $OUTFILE
  echo "runtime:" &>> $OUTFILE
  (time ./bal_sieve $SIZE $nthreads) &>> $OUTFILE
  echo "_____________________________" &>> $OUTFILE
  done

