#!/bin/bash

#SBATCH -t 12:00:00
#SBATCH -n 32
#SBATCH -N 1
#SBATCH -p gpu  
#SBATCH -A rmuniu1
#SBATCH --output=/home/rmuniu1/cs87tests/cuda/results/output_%j.log

OUTFILE=results/testResults$SLURM_JOB_ID

echo " " &>> $OUTFILE
echo "Timing Tests For parallel runs of CUDA Sieve Implementation" &>> $OUTFILE
echo "=============================================================" &>> $OUTFILE

for i in {1..3}
  do
  echo "TEST RUN $i--------------------------------------------------" &>> $OUTFILE
    for n in {1..12}
      do 
        ((SIZE=10**n))
        echo " " &>> $OUTFILE
        echo "n = 1x10^$n " &>> $OUTFILE
        echo "CUDA runtime: " &>> $OUTFILE
        (time ./cudaSieve $SIZE) &>> $OUTFILE
        echo "____________________________________________________________ " &>> $OUTFILE
      done
  done
